controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true


  # joint_trajectory_controller:
  #   type: "joint_trajectory_controller/JointTrajectoryController"


  #   velocity_controller:
  #     type: velocity_controllers/JointGroupVelocityController

    mec_dr_cont:
      type: mecanum_drive_controller/MecanumDriveController
      # type: this_mecanum_drive_controller/This_MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster



# joint_trajectory_controller:
#   ros__parameters:
#     joints:
#       - wheel_joint_fl
#       - wheel_joint_fr
#       - wheel_joint_fl
#       - wheel_joint_fl


#     command_interfaces:
#       - position

#     state_interfaces:
#       - position
#       - velocity

#     action_monitor_rate: 20.0

#     allow_partial_joints_goal: false
#     interpolate_from_desired_state: true
#     constraints:
#       stopped_velocity_tolerance: 0.01
#       goal_time: 0.0
#       joint1:
#         trajectory: 0.05
#         goal: 0.03



mec_dr_cont:
  ros__parameters:
    reference_timeout: 0.5 #0.1
   


    front_left_wheel_command_joint_name: "wheel_joint_fl"
    front_right_wheel_command_joint_name: "wheel_joint_fr"
    rear_right_wheel_command_joint_name: "wheel_joint_br"
    rear_left_wheel_command_joint_name: "wheel_joint_bl"
    
    

    front_left_wheel_state_joint_name: "wheel_joint_fl"
    front_right_wheel_state_joint_name: "wheel_joint_fr"
    rear_right_wheel_state_joint_name: "wheel_joint_br"
    rear_left_wheel_state_joint_name: "wheel_joint_bl"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.3855  
      #sum_of_robot_center_projection_on_X_Y_axis: 0.386  


    publish_odom: true
    enable_odom_tf: true
    publish_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
   
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]


