joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  publish_rate: 50

mec_dr_cont:
  type: position_controllers/JointGroupPositionController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
