joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.3
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.12
      y: 0.12
    scale_linear_turbo:
      x: 0.3
      y: 0.3

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.12
    scale_angular_turbo:
      yaw: 0.3


    enable_button: 6
    enable_turbo_button: 7
    publish_stamped_twist: true
    require_enable_button: false